### ISSUE TITLE
STATE3.EXT fixed-72 formatted but fixed-132 needed by CMAQ

### ISSUE THREAD

**Issue by neumannd** [cjcoats/ioapi-3.2#3]
I wasn't sure whether I should report this issue to the CMAQ or to the IOAPI GitHub repository. I chose to report it here and hope that it is the correct place. 

I am compiling CMAQ 5.2.1 with Intel 2015 compiler suite. By default `-fixed -132` is set as flags for `*.F` files (when using gnu instead of intel, the corresponding flags are set). The Intel Fortran compiler assumes that the included EXT files also conform with `-fixed -132`. The `STATE3.EXT` is not fixed-132 but fixed-72 formatted. Thus, an error is thrown when the file `pinterpb.f` is compiled:

```
ftn -c -fixed -132 -O3 -fno-alias -mp1 -fp-model source -I /home/mvkdneum/CMAS/CMAQ_v5.2.1/lib/x86_64/intel15/ioapi/modules -I /home/mvkdneum/CMAS/CMAQ_v5.2.1/lib/x86_64/intel15/ioapi/include_files -I /home/mvkdneum/CMAS/CMAQ_v5.2.1/lib/x86_64/intel15/mpi -I. pinterpb.f
/home/mvkdneum/CMAS/CMAQ_v5.2.1/lib/x86_64/intel15/ioapi/include_files/STATE3.EXT(174): error #5082: Syntax error, found '&' when expecting one of: <IDENTIFIER>
        COMMON  / BSTATE3 /                                             &
------------------------------------------------------------------------^
...
```

If the `&` is moved to column 133, the compilation works fine. I am not sure how to solve this issue in the CMAQ build script. Hence, I post it here.

I currently work on a cluster by Cray. Therefore, you see `ftn` (a wrapper for ifort) instead of `ifort`. Several relevant flags are not shown because they are included in the `ftn` wrapper.

**Comment by cjcoats** [comment]
Daniel Neumann wrote:
> I wasn't sure whether I should report this issue to the CMAQ or to the
> IOAPI GitHub repository. I chose to report it here and hope that it is the
> correct place.
>
> I am compiling CMAQ 5.2.1 with Intel 2015 compiler suite. By default
> |-fixed -132| is set as flags for |*.F| files (when using gnu instead of
> intel, the corresponding flags are set). The Intel Fortran compiler
> assumes that the included EXT files also conform with |-fixed -132|. The
> |STATE3.EXT| is not fixed-132 but fixed-72 formatted. Thus, an error is
> thrown when the file |pinterpb.f| is compiled:
[etc...]


This has been documented numerous times and in numerous places, including
the CMAQ, the SMOKE, and the I/O API installation instructions, and 
troubleshooting pages, as well as here. See

https://cjcoats.github.io/ioapi/AVAIL.html#cmaq

The ISO Fortran Standard defines exactly two source forms for Fortran
source code, and a particular variant which satisfies both forms.

The I/O API is coded in conformity with that both-forms source format
provided for by the Fortran Standard.

CMAQ chooses *not* to conform to the Fortran standard, using instead a
non-Standard "Fixed-132" format. As a convenience for CMAQ users, the
I/O API has provided a supported method of creating CMAQ-compliant
INCLUDE-files for almost twenty years, and this fact is documented
in both the CMAQ and the I/O API documentation: "make fixed_src"
creates an I/O API sub-directory with fixed-132 versions of the INCLUDE
files for use by CMAQ.

That is what you need to do.

-- 

Carlie J. Coats, Jr., Ph.D.                I/O API Author/Maintainer
6502 Glen Forest Dr.                            home: (919) 493-7695
Chapel Hill, NC  27517                        carlie@jyarborough.com

**Comment by neumannd** [comment]
OK. Thanks. Excuse me for not checking whether this is a known issue.
