### ISSUE TITLE
Issue Compiling ioapi large

### ISSUE THREAD

**Issue by loudlumi** [cjcoats/ioapi-3.2#6]
Any pointers or updated documentation on compiling ioapi large.

I run into an error when compiling large

**Comment by cjcoats** [comment]
I presume you've read the build-instructions https://cjcoats.github.io/ioapi/AVAIL.html#build
(where you copy PARMS3-LARGE.EXT to PARMS3.EXT and proceed according to the instructions).

What was the error?  ...what compiler?  ...what binary-tupe BIN?


Carlie J. Coats, Jr., Ph.D.                    ***@***.***
Senior Software Engineer                   I/O API Author/Maintainer
Center for Environmental Modeling for Policy Development,
UNC Institute for the Environment                     www.ie.unc.edu
100 Europa Dr., Suite 490 Rm 4051 / Campus Box 1105     919.843.5951
Chapel Hill, NC 27599-1105                          Fax 919.966.9920

________________________________
From: loudlumi ***@***.***>
Sent: Wednesday, April 7, 2021 12:19 PM
To: cjcoats/ioapi-3.2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cjcoats/ioapi-3.2] Issue Compiling ioapi large (#6)


Any pointers or updated documentation on compiling ioapi large.

I run into an error when compiling large
